sessionName: force_pyramid
outputSuffix: force_pyramid-file.yml
interBlockInterval: 2000
triggers: [ "5", "7" ] # optional. If missing, the task will start as soon as the "Start" button is clicked
colours: # optional
  leftReference: 1D8348
  leftForce: 82E0AA
forceProportionRange:
  min: 0.00
  max: 1.00
blocks:
  - name: "Block1"
    instructions: "Block1 starting"
    instructionsDuration: 2000
    feedback: "Block1 finished"
    feedbackDuration: 2000
    interTrialInterval: 1000
    trials:
      - name: "1_pyramid"
        sequenceRef: "pyramid"

sequences:
  pyramid:
    frequency: 3000
    valuesLeft: [.05,.2,.4,.6,.6,.4,.2,.05]